### PR TITLE
Feature/ns 7 support

### PR DESCRIPTION
**Pull request by jerbob92**
This MR adds NS7 support, and I also changed some other stuff:
 - Added support for Github Actions to test build
 - Cleaned up config (like gitignore, tslint)
 - Replaced nativescript-permissions with @nativescript-community/perms
 - Moved the native code into this repo (from https://github.com/jibon57/MultiType-FilePicker) and applied the [two open MR's](https://github.com/jibon57/MultiType-FilePicker/pulls) so thumbnails work again on Android 10 and to fix a nullpointerexception

I created a npm package in my fork (https://github.com/klippa-app/nativescript-mediafilepicker/releases/tag/4.0.0) that you can already add to your project to get this to work in NS7.
 - Download the tgz
 - Create a folder inside your repository, like "plugins"
 - Add the tgz to this folder
 - Execute the command `ns plugin add plugins/nativescript-mediafilepicker-4.0.0.tgz`
 - Enjoy!

### CODE REVIEW

**Comment by jibon57** [comment]
Thank you! I've sent you an invitation for collaborator

**Comment by jerbob92** [comment]
@jibon57 thanks! What about NPM? Will you publish a new version? I will update the docs later for different version support.

**Comment by jibon57** [comment]
@jerbob92 can I get your NPM username please?

**Comment by jerbob92** [comment]
@jibon57 it's jerbob92 :D

**Comment by jibon57** [comment]
Thank you! I have sent you invitation. Thanks for your contribution.

**Pull request merged**
